/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_polyfx_jssembly_Jssembly */

#ifndef _Included_com_polyfx_jssembly_Jssembly
#define _Included_com_polyfx_jssembly_Jssembly
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     com_polyfx_jssembly_Jssembly
	* Method:    invoke
	* Signature: ([BI[Ljava/lang/Object;)Ljava/lang/Object;
	*/
	JNIEXPORT void JNICALL Java_com_polyfx_jssembly_Jssembly_invoke
		(JNIEnv *, jobject, jbyteArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
