/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_polyfx_jssembly_Jssembly_Function */

#ifndef _Included_com_polyfx_jssembly_Jssembly_Function
#define _Included_com_polyfx_jssembly_Jssembly_Function
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
